# -*- coding: utf-8 -*-
"""Task 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VM8IPPeuxGWs7MUWbLlxGSdbnGn8q4q0
"""

import pandas as pd

file_path = "/mnt/data/Titanic-Dataset.csv"

df = pd.read_csv("Titanic-Dataset.csv")

basic_info = {
    "Shape": df.shape,
    "Column Names": df.columns.tolist(),
    "Data Types": df.dtypes,
    "Null Values": df.isnull().sum()
}

df.fillna({'Age': df['Age'].mean(), 'Cabin': 'Unknown', 'Embarked': df['Embarked'].mode()[0]}, inplace=True)

missing_after_imputation = df.isnull().sum()

missing_after_imputation
from sklearn.preprocessing import LabelEncoder

df_encoded = df.copy()

le_sex = LabelEncoder()
df_encoded['Sex'] = le_sex.fit_transform(df_encoded['Sex'])

le_embarked = LabelEncoder()
df_encoded['Embarked'] = le_embarked.fit_transform(df_encoded['Embarked'])

le_cabin = LabelEncoder()
df_encoded['Cabin'] = le_cabin.fit_transform(df_encoded['Cabin'])

df_encoded[['Sex', 'Embarked', 'Cabin']].head()
from sklearn.preprocessing import StandardScaler

numerical_features = ['Age', 'Fare', 'SibSp', 'Parch']

scaler = StandardScaler()

df_encoded[numerical_features] = scaler.fit_transform(df_encoded[numerical_features])

df_encoded[numerical_features].head()

import matplotlib.pyplot as plt

import seaborn as sns

sns.set(style="whitegrid")

plt.figure(figsize=(14, 8))

for i, feature in enumerate(numerical_features, 1):
    plt.subplot(2, 2, i)
    sns.boxplot(y=df_encoded[feature])
    plt.title(f'Boxplot of {feature}')

plt.tight_layout()
plt.show()

Q1 = df['Fare'].quantile(0.25)

Q3 = df['Fare'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR

upper_bound = Q3 + 1.5 * IQR

df = df[(df['Fare'] >= lower_bound) & (df['Fare'] <= upper_bound)]

df = df.sort_index(axis=1)

output_path = 'Final_Cleaned_Titanic.csv'

df.to_csv(output_path, index=False)

print(f"\nCleaned dataset saved successfully as '{output_path}'")

from google.colab import files

files.download('Final_Cleaned_Titanic.csv')